<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260717212340 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tool_invocation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tool VARCHAR(64) NOT NULL, input JSON NOT NULL, blocked BOOLEAN NOT NULL, result_summary TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE email_log');
        $this->addSql('DROP TABLE exfiltration_event');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE email_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recipient VARCHAR(255) NOT NULL, body TEXT NOT NULL, blocked BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exfiltration_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tool VARCHAR(64) NOT NULL, domain VARCHAR(255) NOT NULL, url TEXT NOT NULL, query TEXT DEFAULT NULL, blocked BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE tool_invocation');
    }
}
